export const HANDLE_KEYPRESS = 'handle_keypress'
export const HANDLE_CRASH = 'handle_crash'
export const REVERT_POSITION = 'revert_position'
export const RECEIVE_POSITION = 'receive_position'
export const SEND_POSITION = 'send_position'
